Bootstrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/ 
Include: yum

%files
packages.txt packages.txt

%post
yum update -q -y
yum install -y epel-release
yum install -y $(cat packages.txt)
localedef -i en_US -f UTF-8 en_US.UTF-8
rm -f /packages

INSTALL_PKGS="rh-python36 rh-python36-python-devel rh-python36-python-setuptools \
        rh-python36-python-pip rh-python36-numpy rh-python36-python-tkinter rh-python36-python-six\
        nss_wrapper httpd24 httpd24-httpd-devel httpd24-mod_ssl httpd24-mod_auth_kerb httpd24-mod_ldap \
        httpd24-mod_session atlas-devel gcc-gfortran libffi-devel libtool-ltdl enchant tmux" && \
    yum install -y centos-release-scl && \
    yum -y --setopt=tsflags=nodocs install --enablerepo=centosplus $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    # Remove centos-logos (httpd dependency) to keep image size smaller.
    rpm -e --nodeps centos-logos && \
    yum -y clean all --enablerepo='*'
rm -rf /var/cache/yum
 
export PATH=/opt/rh/rh-python36/root/usr/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/rh/rh-python36/root/usr/share/man:$MANPATH
export PKG_CONFIG_PATH=/opt/rh/rh-python36/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
export XDG_DATA_DIRS="/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

mkdir /usr/src/root
cd /usr/src/root
/usr/bin/wget https://root.cern.ch/download/root_v6.13.08.source.tar.gz
tar -xvzf root_v6.13.08.source.tar.gz 

source_dir=/usr/src/root/root-6.13.08

cmake3 $source_dir \
    -Dall=ON \
    -Dcxx11=ON \
    -Dfail-on-missing=ON \
    -Dgnuinstall=ON \
    -Drpath=ON \
    -Dbuiltin_afterimage=OFF \
    -Dbuiltin_ftgl=OFF \
    -Dbuiltin_gl2ps=OFF \
    -Dbuiltin_glew=OFF \
    -Dbuiltin_tbb=ON \
    -Dbuiltin_unuran=OFF \
    -Dbuiltin_vdt=ON \
    -Dbuiltin_veccore=ON \
    -Dbuiltin_xrootd=ON \
    -Darrow=OFF \
    -Dcastor=OFF \
    -Dchirp=OFF \
    -Dgeocad=OFF \
    -Dglite=OFF \
    -Dhdfs=OFF \
    -Dmonalisa=OFF \
    -Doracle=OFF \
    -Dpythia6=OFF \
    -Drfio=OFF \
    -Droot7=OFF \
    -Dsapdb=OFF \
    -Dsrp=OFF \
    -Dvc=OFF \
    -Droofit=ON\
    -Dminuit2=ON\
    -DPYTHON_EXECUTABLE=/opt/rh/rh-python36/root/usr/bin/python3.6
cmake3 --build . -- -j 4
cmake3 --build . --target install
rm -rf /usr/src/root
cd
/opt/rh/rh-python36/root/usr/bin/pip install \
    scipy \
    root-numpy \
    pandas \
    jupyterlab \
    jupyter \
    matplotlib \
    theano \
    scikit-learn \
    keras \
    tensorflow \
    seaborn \
    xgboost \
    root_pandas \
    tqdm \
    ipympl \
    uncertainties

mkdir -p /afs
mkdir -p /eos
mkdir -p /net
mkdir -p /fhgfs

%environment
PYTHONPATH=/usr/local/lib/root:$PYTHONPATH
export PYTHONPATH
export PATH=/opt/rh/rh-python36/root/usr/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/opt/rh/rh-python36/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export MANPATH=/opt/rh/rh-python36/root/usr/share/man:$MANPATH
export PKG_CONFIG_PATH=/opt/rh/rh-python36/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
export XDG_DATA_DIRS="/opt/rh/rh-python36/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
